# -*- coding: utf-8 -*-
"""Employee_Attrition_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvoaTWkbpA0hsGWN04QQqPFVkIMCjc_J

Employee Attrition Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPMPOh3fLQYGuvhOph_LKJxRpT4bSxoH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.decomposition import PCA

#df = pd.read_csv("/content/Emp_attrition_csv.csv") #in colab
df = pd.read_csv("C:/coding/python/Machine Learning/Data/Emp_attrition_csv.csv") # in vs
df = df.drop(columns="Employee ID")

print(df.shape)
df.head(10)

(df.info())

print("\nMessing:\n" , df.isnull() . sum())

(df.describe(include="all"))

# Discover outlaiers
sns.boxplot(x=df['Distance from Home'])
plt.show()
sns.boxplot(x=df["Company Tenure (In Months)"])
plt.show()

sns.boxplot(x=df["Monthly Income"])
plt.show()

# with mean coz no outlaiers
df["Distance from Home"] = df["Distance from Home"].fillna(df["Distance from Home"].mean())

df["Company Tenure (In Months)"] = df["Company Tenure (In Months)"].fillna(df["Company Tenure (In Months)"].mean())
df.info()
print(df.isnull().sum())
df = df.dropna()

# Target Balanced
sns.countplot(x="Attrition", data=df)
plt.title("Target Distribution")
print(df['Attrition'].value_counts())

df = df.drop_duplicates()

object_cols = df.select_dtypes(include=["object", "category"]).columns

for col in object_cols:
    print(f"\n {col}:")
    print(df[col].value_counts())

worklife_map = {"Poor":0, "Fair":1, "Good":2, "Excellent":3}
jobsat_map = {"Low":0, "Medium":1, "High":2, "Very High":3}
joblevel_map = {"Entry":0, "Mid":1, "Senior":2}
reputation_map = {"Poor":0, "Fair":1, "Good":2, "Excellent":3}
recognition_map = {"Low":0, "Medium":1, "High":2, "Very High":3}
education_map = {
    "High School": 0,
    "Associate Degree": 1,
    "Bachelorâ€™s Degree": 2,
    "Masterâ€™s Degree": 3,
    "PhD": 4
}
performance_map = {
    "Low": 0,
    "Below Average": 1,
    "Average": 2,
    "High": 3
}

df["Performance Rating"] = df["Performance Rating"].map(performance_map)
df["Education Level"] = df["Education Level"].map(education_map)
df["Work-Life Balance"] = df["Work-Life Balance"].map(worklife_map)
df["Job Satisfaction"] = df["Job Satisfaction"].map(jobsat_map)
df["Job Level"] = df["Job Level"].map(joblevel_map)
df["Company Reputation"] = df["Company Reputation"].map(reputation_map)
df["Employee Recognition"] = df["Employee Recognition"].map(recognition_map)

df = pd.get_dummies(df, columns=[
    "Overtime","Remote Work","Leadership Opportunities",
    "Innovation Opportunities","Attrition"
], drop_first=True, dtype=int)

label_cols = ["Gender","Job Role","Marital Status","Company Size"]
le = LabelEncoder()
for col in label_cols:
    df[col] = le.fit_transform(df[col])

(df.head(10))

plt.figure(figsize=(14, 10))
sns.heatmap(
    df.corr(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5,
    cbar_kws={"shrink": 0.8}
)
plt.title("Correlation Matrix", fontsize=16, fontweight="bold")
plt.xticks(rotation=45, ha="right", fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()

#print(df.columns)
x = df.drop(columns="Attrition_Stayed")
y = df["Attrition_Stayed"]
##############################################################################################################
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size =.2 , random_state= 42 , stratify= y)
##############################################################################################################

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

pca = PCA()
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix

rf_model = RandomForestClassifier(
    n_estimators = 600,
    random_state = 42,
    max_depth = 1
)
rf_model.fit(x_train, y_train)

y_pred = rf_model.predict(x_test)
y_proba = rf_model.predict_proba(x_test)[:, 1]

# ---------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_proba)

print("Random Forest - Performance Metrics")
print("=" * 40)
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {auc:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=["Left", "Stayed"]))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))




from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier


param_grid = {
    "n_estimators": [100, 300, 500, 600, 1000],
    "max_depth": [1, 2, 3, 5, 7, 10, 15],   
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
}
random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_distributions=param_grid,
    n_iter=10,          
    scoring="accuracy",
    cv=5,
    n_jobs= -1,
    random_state=42,
    verbose=2
)

random_search.fit(x_train_scaled, y_train)
print("Best Parameters:", random_search.best_params_)
print("Best CV Score  :", random_search.best_score_)


